### ISSUE TITLE
Support other variants of phpcs.xml

### ISSUE THREAD

**Issue by GaryJones** [m-e-h/theme-claim#2]
PHPCS 3.1+ supports other variants of the `phpcs.xml` file:
- `.phpcs.xml.dist`
- `phpcs.xml.dist`
- `.phpcs.xml`

These should be supported where `phpxs.xml` [is](https://github.com/m-e-h/theme-claim/blob/0060ad1e56bcaa489968ad8225bded8bf5e50675/lib/replace.js#L93).

**Comment by m-e-h** [comment]
Thanks @GaryJones !

**Comment by GaryJones** [comment]
What about `phpcs.xml.dist`? That doesn't seem to have been included.

**Comment by m-e-h** [comment]
Doh! Thanks again!
