### ISSUE TITLE
Replace namespace in composer.json

### ISSUE THREAD

**Issue by justintadlock** [m-e-h/theme-claim#4]
Reported on the Slack channel that `Mythic` doesn't get replaced in the autoload section of `composer.json`:

```
"autoload"    : {
	"psr-4" : {
		"Mythic\\" : "app/"
	}
},
```

**Comment by m-e-h** [comment]
Fixed in https://github.com/m-e-h/theme-claim/commit/7de576f1d58d1f719e6986ed1ba7dd4d15012577
