### ISSUE TITLE
Error npm run rename if ThemeName is written in CamelCaseNotation (in Mythic theme)

### ISSUE THREAD

**Issue by MrAndreius** [m-e-h/theme-claim#7]
https://github.com/justintadlock/mythic/issues/73

Fatal error: Uncaught Error: Class 'ThemeName\Providers\AppServiceProvider' not found in .......\wp-content\themes\themename\vendor\justintadlock\hybrid-core\src\Core\Application.php on line 187

To make it work, need to manually correct the class name in the files. Themename = > ThemeName
vendor\composer\autoload_static.php
vendor\composer\autoload_psr4.php

**Comment by m-e-h** [comment]
Thanks @MrAndreius! I'll update in a bit.
